ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50) NOT NULL DEFAULT 'PRO';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE restaurants ADD COLUMN IF NOT EXISTS subscription_end_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 days');
